import Header from "./components/header";
import "./globals.css";
import { Arbutus } from "next/font/google";

const inter = Arbutus({ subsets: ["latin"], weight: "400" });

export const metadata = {
  title: "Team blog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}
